name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      terraform_version: "1.5.2"
      working_directory: "./terraform"
