name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      terraform_version: "1.5.2"
      working_directory: "./terraform"
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
