name: Reusable Terraform Workflow

on:
  workflow_call:
    inputs:
      terraform_version:
        description: "The Terraform version to use"
        default: "1.5.2"
        type: string
      working_directory:
        description: "Directory containing Terraform files"
        default: "./terraform"
        type: string
      aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
        type: string
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true
        type: string
      aws_session_token:
        description: "AWS Session Token"
        required: true
        type: string

jobs:
  validate-plan:
    name: Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ inputs.working_directory }}

      - name: Print environment variables (for debugging, should be removed in production)
        run: printenv
        env:
          AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}

      - name: Validate Terraform
        run: terraform validate
        working-directory: ${{ inputs.working_directory }}

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: ${{ inputs.working_directory }}
        env:
          AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}

  deploy:
    name: Deploy
    needs: validate-plan
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ inputs.working_directory }}
        env:
          AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}

      - name: Print environment variables (for debugging, should be removed in production)
        run: printenv
        env:
          AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
